spring.application.name=GitHubGroupC

# データベース接続用
spring.jpa.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgrestest

# mybatis用
mybatis.mapper-locations=classpath:mapper/**/*.xml

# Server設定
server.port=8080
server.servlet.context-path=/
