# Application Configuration
spring.application.name=ECSample

# データベース接続用
spring.jpa.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgrestest

# JPA/Hibernate設定　一番上はテーブル設定が完成したら消す
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleafテンプレート設定
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Server設定
server.port=8080
server.servlet.context-path=/

# ロギング設定（フレームワークのログ出力レベルの設定）完成したら消す
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# 開発支援設定（自動更新系ないほうが軽いかも）
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true